Revert "nouns : again 'error[E0432]: unresolved import ethers::prelude::contract' after  cargo update"
This reverts commit 50359780aaab13ca54ed4a33f826f546590d89e4.